repos:
  - repo: local
    hooks:
      - id: bun-format
        name: bun format
        entry: bun format
        language: system
        types_or: [javascript, ts]
        pass_filenames: false
        always_run: true
